# Generated by Django 6.0.4 on 2026-05-01 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apic_connections", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("queries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AWXConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(max_length=255)),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("token", "OAuth2 Token"),
                            ("basic", "Username/Password"),
                        ],
                        default="token",
                        max_length=20,
                    ),
                ),
                ("encrypted_token", models.BinaryField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("encrypted_password", models.BinaryField(blank=True, null=True)),
                ("verify_ssl", models.BooleanField(default=True)),
                ("timeout", models.IntegerField(default=30)),
                (
                    "credential_prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional case-sensitive prefix to filter AWX credentials (e.g. 'CISCO_ACI_'). Leave blank to list all credentials.",
                        max_length=100,
                    ),
                ),
                ("awx_version", models.CharField(blank=True, max_length=50, null=True)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_test_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awx_connections_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="awx_connections_shared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "awx_connections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "awx_type",
                    models.CharField(
                        choices=[
                            ("job_template", "Job Template"),
                            ("workflow_template", "Workflow Template"),
                        ],
                        help_text="Job Template or Workflow Template",
                        max_length=20,
                    ),
                ),
                (
                    "awx_template_id",
                    models.IntegerField(
                        help_text="AWX Job Template ID or Workflow Template ID"
                    ),
                ),
                (
                    "awx_template_name",
                    models.CharField(help_text="Cached name from AWX", max_length=200),
                ),
                (
                    "workflow_job_nodes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='\n        Workflow job nodes in execution order (fetched from AWX).\n        Example:\n        [\n            {\n                "order": 1,\n                "job_template_id": 42,\n                "name": "Create L3Out",\n                "identifier": "node-1"\n            },\n            {\n                "order": 2,\n                "job_template_id": 43,\n                "name": "Configure BGP",\n                "identifier": "node-2"\n            }\n        ]\n        ',
                    ),
                ),
                (
                    "table_schemas",
                    models.JSONField(
                        default=list,
                        help_text='\n        Table schemas for data input. Each schema represents one Excel sheet.\n\n        For Job Template (single playbook):\n        [\n            {\n                "sheet_name": "Tenants",\n                "job_template_id": null,\n                "columns": [\n                    {\n                        "name": "tenant_name",\n                        "display_name": "Tenant Name",\n                        "type": "text",\n                        "required": true,\n                        "validation": "^[a-zA-Z0-9_-]{1,64}$",\n                        "help_text": "Alphanumeric, dash, underscore only"\n                    }\n                ],\n                "min_rows": 1,\n                "max_rows": 100\n            }\n        ]\n\n        For Workflow Template (multiple playbooks):\n        [\n            {\n                "sheet_name": "Create_L3Out",\n                "job_template_id": 42,\n                "columns": [...]\n            },\n            {\n                "sheet_name": "Configure_BGP",\n                "job_template_id": 43,\n                "columns": [...]\n            }\n        ]\n        ',
                    ),
                ),
                (
                    "variable_mappings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Maps table column data to AWX extra_vars.\n        Example:\n        {\n            "tenant_name": "tenant",\n            "vrf_name": "vrf"\n        }\n        ',
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="List of tags for filtering (e.g., ['l3out', 'bgp', 'bfd'])",
                    ),
                ),
                (
                    "requires_validation",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Requires column validation before execution",
                    ),
                ),
                (
                    "allow_validation_bypass",
                    models.BooleanField(
                        default=False,
                        help_text="Allow users with 'awx.bypass_validation' permission to skip validation",
                    ),
                ),
                (
                    "enable_check_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable Ansible check mode (dry-run) by default for this template",
                    ),
                ),
                (
                    "allow_check_mode_override",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to override check mode setting when creating requests",
                    ),
                ),
                ("execution_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[("bulk", "Bulk (Single Job)")],
                        default="bulk",
                        help_text="All rows are sent as structured JSON in a single AWX job.",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "auto_approve_for_owner",
                    models.BooleanField(
                        default=False,
                        help_text="Skip approval when the requester owns the template",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver_groups",
                    models.ManyToManyField(
                        blank=True, related_name="approvable_templates", to="auth.group"
                    ),
                ),
                (
                    "approver_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="approvable_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rollback_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollback_for",
                        to="awx.automationtemplate",
                    ),
                ),
                (
                    "awx_connection",
                    models.ForeignKey(
                        help_text="AWX connection to use",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="awx.awxconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automation Template",
                "verbose_name_plural": "Automation Templates",
                "db_table": "awx_automation_template",
                "ordering": ["-created_at"],
                "permissions": [
                    ("bypass_validation", "Can bypass validation for templates")
                ],
            },
        ),
        migrations.CreateModel(
            name="AutomationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "awx_credential_id",
                    models.IntegerField(
                        blank=True,
                        help_text="AWX Credential ID for target device authentication",
                        null=True,
                    ),
                ),
                (
                    "awx_credential_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cached credential name from AWX (display only)",
                        max_length=200,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        help_text="User-provided data from tables (structured by sheet name)"
                    ),
                ),
                (
                    "ansible_extra_vars",
                    models.JSONField(
                        blank=True,
                        help_text="Transformed extra_vars for AWX",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_approval", "Awaiting Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "check_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Run in Ansible check mode (dry-run, no changes applied)",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "awx_job_id",
                    models.IntegerField(
                        blank=True, help_text="AWX job ID or workflow job ID", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="\n        Request metadata for audit trail:\n        - client_ip: Client IP address\n        - user_agent: Browser user agent\n        - session_id: Django session ID\n        - ldap_attributes: LDAP user attributes (if LDAP enabled)\n        - geo_location: IP geolocation (optional)\n        ",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("template_snapshot", models.JSONField(blank=True, null=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_awx_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_apic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target APIC (if required)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_requests",
                        to="apic_connections.apicconnection",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="awx.automationtemplate",
                    ),
                ),
                (
                    "awx_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="awx.awxconnection",
                    ),
                ),
            ],
            options={
                "db_table": "awx_automation_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "awx_job_id",
                    models.IntegerField(
                        blank=True, help_text="AWX job ID or workflow job ID", null=True
                    ),
                ),
                ("awx_job_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "awx_job_data",
                    models.JSONField(
                        default=dict,
                        help_text="Complete AWX job/workflow JSON response",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("waiting", "Waiting"),
                            ("running", "Running"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                (
                    "current_task",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("result_traceback", models.TextField(blank=True, null=True)),
                ("artifacts", models.JSONField(default=dict)),
                ("playbook_counts", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("elapsed_seconds", models.FloatField(blank=True, null=True)),
                (
                    "execution_mode",
                    models.CharField(
                        blank=True,
                        help_text="Execution mode used (always bulk for new executions)",
                        max_length=20,
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Row number for per-row mode (1-indexed)",
                        null=True,
                    ),
                ),
                (
                    "batch_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Batch number (legacy, no longer populated)",
                        null=True,
                    ),
                ),
                (
                    "row_range",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Row range for this execution.\n        Example: {"start": 0, "end": 20} for rows 0-19 (0-indexed)\n        ',
                    ),
                ),
                (
                    "execution_metadata",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Additional execution metadata.\n        Example: {"total_rows": 100, "retry_of_execution": "uuid", "scm_url": "..."}\n        ',
                    ),
                ),
                (
                    "relaunch_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Depth in relaunch chain (0 = original, 1 = first relaunch, ...)",
                    ),
                ),
                (
                    "clone_template_id",
                    models.IntegerField(
                        blank=True,
                        help_text="AWX workflow_job_template ID of the ephemeral clone (workflow only)",
                        null=True,
                    ),
                ),
                ("row_results", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relaunch_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original execution this was relaunched from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relaunches",
                        to="awx.automationexecution",
                    ),
                ),
                (
                    "automation_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="awx.automationrequest",
                    ),
                ),
                (
                    "awx_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="awx.awxconnection",
                    ),
                ),
            ],
            options={
                "db_table": "awx_automation_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ColumnTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "column_data",
                    models.JSONField(
                        help_text='\n        Full column definition.\n        Example:\n        {\n            "name": "tenant_name",\n            "display_name": "Tenant Name",\n            "type": "text",\n            "required": true,\n            "validation": "^[a-zA-Z0-9_-]{1,64}$",\n            "help_text": "Alphanumeric, dash, underscore only",\n            "min_length": 1,\n            "max_length": 64\n        }\n        '
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("user", "User Template"),
                            ("company", "Company-wide Template"),
                        ],
                        default="user",
                        help_text="Template scope: user-specific or company-wide",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="True if publicly available to all users",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this template has been applied",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="column_templates_shared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Column Template",
                "verbose_name_plural": "Column Templates",
                "db_table": "awx_column_template",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobOutputChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "awx_job_id",
                    models.IntegerField(
                        db_index=True, help_text="AWX job ID for this output"
                    ),
                ),
                (
                    "counter",
                    models.IntegerField(help_text="AWX job_event counter for ordering"),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event type: runner_on_ok, runner_on_failed, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "stdout",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Standard output from this event",
                    ),
                ),
                (
                    "stderr",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Standard error from this event",
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional event data (task name, play name, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "awx_created",
                    models.DateTimeField(help_text="Original event timestamp from AWX"),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_chunks",
                        to="awx.automationexecution",
                    ),
                ),
            ],
            options={
                "db_table": "awx_job_output_chunks",
                "ordering": ["counter"],
            },
        ),
        migrations.CreateModel(
            name="RegexPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique pattern name (e.g., 'IPv4 Address')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Explain what this pattern matches and when to use it",
                    ),
                ),
                (
                    "pattern",
                    models.TextField(
                        help_text="The regex pattern string (e.g., '^[a-zA-Z0-9_-]+$')"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("network", "Network"),
                            ("naming", "Naming Convention"),
                            ("format", "Data Format"),
                            ("security", "Security"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "test_strings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sample test strings saved with the pattern [{'value': '...', 'should_match': true}]",
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Regex flags: ['i'] for case-insensitive, ['m'] for multiline, etc.",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        help_text="Custom error message when a value doesn't match",
                        max_length=500,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Visible to all users (vs. creator only)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Number of columns using this pattern"
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regex_patterns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Regex Pattern",
                "verbose_name_plural": "Regex Patterns",
                "db_table": "awx_regex_pattern",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color code for UI (e.g., #6366f1)",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name (e.g., 'network', 'server')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Sort order in UI"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System categories cannot be deleted or renamed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Category",
                "verbose_name_plural": "Template Categories",
                "db_table": "awx_template_category",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="automationtemplate",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="awx.templatecategory",
            ),
        ),
        migrations.CreateModel(
            name="ValidationList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique validation list name (e.g., 'ACI Tenant Names')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Explain what this list validates and why"
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        help_text="Array of allowed values ['value1', 'value2', ...]"
                    ),
                ),
                (
                    "case_sensitive",
                    models.BooleanField(
                        default=False, help_text="Case-sensitive matching"
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        help_text="Error message shown when value not in list (max 500 chars)",
                        max_length=500,
                    ),
                ),
                (
                    "error_message_title",
                    models.CharField(
                        help_text="Short error title (max 100 chars)", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Visible to all users (vs. creator only)",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Number of columns using this list"
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_lists_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation List",
                "verbose_name_plural": "Validation Lists",
                "db_table": "awx_validation_list",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sheet_name", models.CharField(max_length=200)),
                ("column_name", models.CharField(max_length=200)),
                (
                    "validation_type",
                    models.CharField(
                        choices=[
                            ("regex", "Regex Pattern"),
                            ("static_list", "Static List"),
                            ("query_list", "Query List"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_usages_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_usages",
                        to="awx.automationtemplate",
                    ),
                ),
                (
                    "validation_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="awx.validationlist",
                    ),
                ),
                (
                    "validation_query",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_usages",
                        to="queries.savedquery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Usage",
                "verbose_name_plural": "Validation Usages",
                "db_table": "awx_validation_usage",
            },
        ),
        migrations.AddIndex(
            model_name="automationrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="awx_automat_status_ebce88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrequest",
            index=models.Index(
                fields=["requested_by", "-created_at"],
                name="awx_automat_request_fc415a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationrequest",
            index=models.Index(
                fields=["template", "-created_at"],
                name="awx_automat_templat_510011_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["automation_request", "-created_at"],
                name="awx_automat_automat_5d06da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["status", "-created_at"], name="awx_automat_status_7d528b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["awx_job_id"], name="awx_automat_awx_job_9ae4ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationexecution",
            index=models.Index(
                fields=["relaunch_of"], name="awx_automat_relaunc_0a4fe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="columntemplate",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="awx_column__created_590de9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="columntemplate",
            index=models.Index(
                fields=["scope", "-usage_count"], name="awx_column__scope_5713e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="columntemplate",
            index=models.Index(
                fields=["is_public", "-usage_count"],
                name="awx_column__is_publ_e61ae9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="joboutputchunk",
            index=models.Index(
                fields=["execution", "counter"], name="awx_job_out_executi_977c55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joboutputchunk",
            index=models.Index(
                fields=["awx_job_id", "counter"], name="awx_job_out_awx_job_2db068_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="joboutputchunk",
            unique_together={("execution", "counter")},
        ),
        migrations.AddIndex(
            model_name="regexpattern",
            index=models.Index(fields=["name"], name="awx_regex_p_name_81d05a_idx"),
        ),
        migrations.AddIndex(
            model_name="regexpattern",
            index=models.Index(
                fields=["category"], name="awx_regex_p_categor_6a8633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regexpattern",
            index=models.Index(
                fields=["-created_at"], name="awx_regex_p_created_177993_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationtemplate",
            index=models.Index(
                fields=["category", "-created_at"],
                name="awx_automat_categor_492f47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationtemplate",
            index=models.Index(
                fields=["awx_type"], name="awx_automat_awx_typ_0552bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationtemplate",
            index=models.Index(
                fields=["is_public"], name="awx_automat_is_publ_2e9041_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationtemplate",
            index=models.Index(fields=["name"], name="awx_automat_name_f74370_idx"),
        ),
        migrations.AddIndex(
            model_name="automationtemplate",
            index=models.Index(
                fields=["requires_validation"], name="awx_automat_require_0c6812_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationlist",
            index=models.Index(fields=["name"], name="awx_validat_name_8cfbb7_idx"),
        ),
        migrations.AddIndex(
            model_name="validationlist",
            index=models.Index(
                fields=["-created_at"], name="awx_validat_created_0e1487_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationusage",
            index=models.Index(
                fields=["validation_list"], name="awx_validat_validat_d6488d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationusage",
            index=models.Index(
                fields=["validation_query"], name="awx_validat_validat_2d01c5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="validationusage",
            unique_together={("template", "sheet_name", "column_name")},
        ),
    ]
