# Generated by Django 6.0.4 on 2026-05-01 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(db_index=True, max_length=255)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("class_pkg", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["class_name"], name="mim_favorit_class_n_95d361_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="mim_favorit_created_8a0e03_idx"
                    ),
                ],
                "unique_together": {("user", "class_name")},
            },
        ),
        migrations.CreateModel(
            name="RecentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(db_index=True, max_length=255)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("class_pkg", models.CharField(blank=True, max_length=100)),
                ("use_count", models.PositiveIntegerField(default=1)),
                (
                    "last_used_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-use_count", "-last_used_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_used_at"],
                        name="mim_recentc_user_id_51950b_idx",
                    ),
                    models.Index(
                        fields=["user", "-use_count"],
                        name="mim_recentc_user_id_44fc68_idx",
                    ),
                    models.Index(
                        fields=["class_name"], name="mim_recentc_class_n_6e0d4b_idx"
                    ),
                ],
                "unique_together": {("user", "class_name")},
            },
        ),
        migrations.CreateModel(
            name="TableTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(db_index=True, max_length=255)),
                ("template_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("columns", models.JSONField(default=list)),
                ("preferences", models.JSONField(default=dict)),
                ("default_filters", models.JSONField(blank=True, default=list)),
                ("default_sorting", models.JSONField(blank=True, default=list)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "class_name"],
                        name="mim_tablete_user_id_fb79bf_idx",
                    ),
                    models.Index(
                        fields=["class_name", "is_default"],
                        name="mim_tablete_class_n_8235d6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTablePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(db_index=True, max_length=255)),
                ("visible_columns", models.JSONField(default=list)),
                ("column_order", models.JSONField(default=list)),
                ("hidden_columns", models.JSONField(default=list)),
                ("always_visible", models.JSONField(default=list)),
                ("auto_hide_empty", models.BooleanField(default=True)),
                (
                    "nested_display",
                    models.CharField(
                        choices=[
                            ("inline-summary", "Inline Summary"),
                            ("inline-expanded", "Inline Expanded"),
                            ("modal", "Modal View"),
                        ],
                        default="inline-summary",
                        max_length=50,
                    ),
                ),
                ("max_inline_children", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "class_name"],
                        name="mim_usertab_user_id_f6ae83_idx",
                    )
                ],
                "unique_together": {("user", "class_name")},
            },
        ),
    ]
