# Generated by Django 6.0.4 on 2026-05-01 13:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIQueryBuilderSettings",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable AI Query Builder feature globally",
                    ),
                ),
                (
                    "ollama_url",
                    models.CharField(
                        default="http://localhost:11434",
                        help_text="Ollama API URL",
                        max_length=255,
                    ),
                ),
                (
                    "intent_model",
                    models.CharField(
                        default="qwen2.5-coder:7b",
                        help_text="Model for intent extraction (fast, lightweight)",
                        max_length=100,
                    ),
                ),
                (
                    "query_builder_model",
                    models.CharField(
                        default="phi3:medium",
                        help_text="Model for query generation (accurate, powerful)",
                        max_length=100,
                    ),
                ),
                (
                    "neo4j_url",
                    models.CharField(
                        default="bolt://localhost:7687",
                        help_text="Neo4j database URL for schema validation",
                        max_length=255,
                    ),
                ),
                (
                    "neo4j_user",
                    models.CharField(
                        default="neo4j", help_text="Neo4j username", max_length=100
                    ),
                ),
                (
                    "neo4j_password",
                    models.CharField(
                        default="password",
                        help_text="Neo4j password (encrypted in production)",
                        max_length=255,
                    ),
                ),
                (
                    "log_all_queries",
                    models.BooleanField(
                        default=True,
                        help_text="Log all AI query generation attempts for debugging",
                    ),
                ),
                (
                    "save_failed_attempts",
                    models.BooleanField(
                        default=True,
                        help_text="Save failed generation attempts for model improvement",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last user who updated settings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Query Builder Settings",
                "verbose_name_plural": "AI Query Builder Settings",
            },
        ),
        migrations.CreateModel(
            name="SavedQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("flow_data", models.JSONField(help_text="React Flow nodes and edges")),
                (
                    "generated_query",
                    models.TextField(help_text="Generated APIC query string"),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False, help_text="Is this a reusable template?"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        help_text="Template variable definitions (id, label, type, binding, etc.)",
                        null=True,
                    ),
                ),
                (
                    "enable_time_machine",
                    models.BooleanField(
                        default=False,
                        help_text="Track execution history in Time Machine",
                    ),
                ),
                (
                    "enable_pagination",
                    models.BooleanField(
                        default=False, help_text="Enable pagination for query results"
                    ),
                ),
                (
                    "page_size",
                    models.IntegerField(
                        default=50, help_text="Number of results per page (max: 1000)"
                    ),
                ),
                (
                    "major_version",
                    models.IntegerField(
                        default=1,
                        help_text="Major version number (increments on structural changes)",
                    ),
                ),
                (
                    "minor_version",
                    models.IntegerField(
                        default=0,
                        help_text="Minor version number (increments on filter/processor changes)",
                    ),
                ),
                (
                    "current_version_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hash of current query structure for change detection",
                        max_length=8,
                    ),
                ),
                (
                    "version_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Version changelog: [{ version, hash, changes, created_at, created_by }]",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Visible to all users"
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(
                        default=0, help_text="Number of times executed"
                    ),
                ),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_validation_query",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Is this query used for validation purposes?",
                    ),
                ),
                (
                    "validation_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this validation query checks",
                    ),
                ),
                (
                    "validation_error_message",
                    models.CharField(
                        blank=True,
                        help_text="Error message to show when validation fails",
                        max_length=500,
                    ),
                ),
                (
                    "validation_error_title",
                    models.CharField(
                        blank=True,
                        help_text="Short error title for validation failures",
                        max_length=100,
                    ),
                ),
                (
                    "validation_value_field",
                    models.CharField(
                        blank=True,
                        help_text='Dotted path to extract list values from APIC response. E.g. "fvTenant.attributes.name" extracts name from each imdata item.',
                        max_length=500,
                    ),
                ),
                (
                    "validation_usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of templates/columns using this validation query",
                    ),
                ),
                (
                    "last_validated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this query was used for validation",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queries",
                        to="queries.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favorited_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Query",
                "verbose_name_plural": "Saved Queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueryExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "result_count",
                    models.IntegerField(
                        blank=True, help_text="Number of results returned", null=True
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="queries.savedquery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Query Execution Log",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="ChainExecutionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_iterations",
                    models.IntegerField(
                        default=0, help_text="Total number of iterations to execute"
                    ),
                ),
                (
                    "completed_iterations",
                    models.IntegerField(
                        default=0, help_text="Successfully completed iterations"
                    ),
                ),
                (
                    "failed_iterations",
                    models.IntegerField(default=0, help_text="Failed iterations"),
                ),
                (
                    "chain_config",
                    models.JSONField(
                        help_text="Chain node configuration (source, extractPath, targetQuery, etc.)"
                    ),
                ),
                (
                    "source_result",
                    models.JSONField(
                        blank=True, help_text="Result from the source query", null=True
                    ),
                ),
                (
                    "extracted_values",
                    models.JSONField(
                        default=list,
                        help_text="Values extracted from source result (DNs, IPs, etc.)",
                    ),
                ),
                (
                    "aggregated_results",
                    models.JSONField(
                        default=list, help_text="Aggregated results from all iterations"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        default=list,
                        help_text="List of errors encountered during execution",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Total execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "avg_iteration_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Average time per iteration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for this execution",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pipeline_stages",
                    models.JSONField(
                        blank=True,
                        help_text="Ordered list of pipeline stage definitions parsed from flow_data",
                        null=True,
                    ),
                ),
                (
                    "current_stage_index",
                    models.IntegerField(
                        default=0,
                        help_text="Index of the currently executing pipeline stage",
                    ),
                ),
                (
                    "execution_mode",
                    models.CharField(
                        default="chain",
                        help_text="Execution mode: chain (legacy iteration) or pipeline (sequential stages)",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the chain execution",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        help_text="The query containing the chain node",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_executions",
                        to="queries.savedquery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chain Execution Job",
                "verbose_name_plural": "Chain Execution Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Task name", max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("apic_query", "APIC Query"),
                            ("system_maintenance", "System Maintenance"),
                            ("system_monitoring", "System Monitoring"),
                            ("system_sync", "External System Sync"),
                            ("system_snapshot", "Snapshot & Backup"),
                        ],
                        db_index=True,
                        default="apic_query",
                        help_text="Type of task (APIC query or system task)",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text='Task category for UI grouping (e.g., "Storage", "Monitoring", "Snapshots")',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_system_task",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="System task (admin-only, managed by platform)",
                    ),
                ),
                (
                    "system_task_handler",
                    models.CharField(
                        blank=True,
                        help_text='Celery task path for system tasks (e.g., "awx.cleanup_old_output_chunks")',
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_index=True,
                        default="medium",
                        help_text="Task priority (affects execution order)",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Manual order within same priority (lower executes first)",
                    ),
                ),
                (
                    "apic_connection_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of APIC connection IDs to execute against",
                    ),
                ),
                (
                    "variable_values",
                    models.JSONField(
                        blank=True,
                        help_text="Variable values for template execution",
                        null=True,
                    ),
                ),
                (
                    "retry_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable automatic retry on failure"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=3, help_text="Number of retry attempts on failure"
                    ),
                ),
                (
                    "retry_interval_minutes",
                    models.IntegerField(
                        default=5, help_text="Minutes to wait between retry attempts"
                    ),
                ),
                (
                    "email_on_success",
                    models.BooleanField(
                        default=False,
                        help_text="Send email notification on successful execution",
                    ),
                ),
                (
                    "email_on_failure",
                    models.BooleanField(
                        default=True,
                        help_text="Send email notification on failed execution",
                    ),
                ),
                (
                    "email_recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of email addresses to notify",
                    ),
                ),
                (
                    "log_retention_days",
                    models.IntegerField(
                        default=30, help_text="Number of days to retain execution logs"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        help_text="Execution frequency",
                        max_length=20,
                    ),
                ),
                (
                    "minute_of_hour",
                    models.IntegerField(
                        blank=True,
                        help_text="Minute of the hour for hourly tasks (0-59)",
                        null=True,
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        blank=True,
                        help_text="Time of day for daily tasks (HH:MM)",
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        help_text="Day of week for weekly tasks",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month for monthly tasks (1-31)",
                        null=True,
                    ),
                ),
                (
                    "scheduled_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Specific datetime for one-time tasks",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for scheduled execution",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, help_text="Last execution time", null=True
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Next scheduled execution time",
                        null=True,
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(
                        default=0, help_text="Number of times executed"
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(
                        default=0, help_text="Number of successful executions"
                    ),
                ),
                (
                    "failure_count",
                    models.IntegerField(
                        default=0, help_text="Number of failed executions"
                    ),
                ),
                (
                    "celery_periodic_task_name",
                    models.CharField(
                        blank=True,
                        help_text="Celery periodic task name",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this task (null for system tasks)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saved_query",
                    models.ForeignKey(
                        blank=True,
                        help_text="Query or template to execute (null for system tasks)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_tasks",
                        to="queries.savedquery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Task",
                "verbose_name_plural": "Scheduled Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTaskExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "apic_connection_id",
                    models.IntegerField(
                        help_text="APIC connection ID used for this execution"
                    ),
                ),
                (
                    "apic_connection_name",
                    models.CharField(
                        blank=True,
                        help_text="APIC connection name (cached for history)",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Query execution result", null=True
                    ),
                ),
                (
                    "result_count",
                    models.IntegerField(
                        blank=True, help_text="Number of results returned", null=True
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        help_text="Error type if failed",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Detailed error message", null=True
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, help_text="Error traceback for debugging", null=True
                    ),
                ),
                (
                    "retry_attempt",
                    models.IntegerField(
                        default=0, help_text="Retry attempt number (0 = first attempt)"
                    ),
                ),
                (
                    "is_retry",
                    models.BooleanField(
                        default=False, help_text="Is this a retry attempt?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Celery task ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "scheduled_task",
                    models.ForeignKey(
                        help_text="The scheduled task that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="queries.scheduledtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Task Execution",
                "verbose_name_plural": "Scheduled Task Executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskManagementSettings",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "default_retry_count",
                    models.IntegerField(
                        default=3, help_text="Default number of retry attempts"
                    ),
                ),
                (
                    "default_retry_interval_minutes",
                    models.IntegerField(
                        default=5, help_text="Default minutes between retry attempts"
                    ),
                ),
                (
                    "default_log_retention_days",
                    models.IntegerField(
                        default=30,
                        help_text="Default number of days to retain execution logs",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable email notifications globally"
                    ),
                ),
                (
                    "email_from_address",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="From email address for notifications",
                        max_length=254,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Last user who updated settings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Management Settings",
                "verbose_name_plural": "Task Management Settings",
            },
        ),
        migrations.CreateModel(
            name="UserAIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("azure_openai", "Azure OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("groq", "Groq"),
                            ("google", "Google AI"),
                            ("openrouter", "OpenRouter"),
                            ("ollama", "Ollama (Local)"),
                        ],
                        default="ollama",
                        help_text="AI provider to use",
                        max_length=20,
                    ),
                ),
                (
                    "api_key",
                    models.BinaryField(
                        blank=True, help_text="Encrypted API key", null=True
                    ),
                ),
                (
                    "api_base_url",
                    models.CharField(
                        blank=True,
                        help_text="Custom API base URL (for Azure, Ollama, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Model to use (e.g., gpt-4o, claude-3-5-sonnet, llama-3.1-70b-versatile)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "azure_deployment_name",
                    models.CharField(
                        blank=True,
                        help_text="Azure OpenAI deployment name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "azure_api_version",
                    models.CharField(
                        blank=True,
                        default="2024-02-15-preview",
                        help_text="Azure OpenAI API version",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this provider configuration active?"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this provider was used",
                        null=True,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Last error message (for debugging)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_provider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User AI Provider",
                "verbose_name_plural": "User AI Providers",
            },
        ),
        migrations.CreateModel(
            name="ChainIterationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iteration_index",
                    models.IntegerField(help_text="Index of this iteration (0-based)"),
                ),
                (
                    "batch_number",
                    models.IntegerField(
                        default=0, help_text="Batch number for grouped execution"
                    ),
                ),
                (
                    "extracted_value",
                    models.TextField(
                        help_text="Value extracted from source (DN, IP, name, etc.)"
                    ),
                ),
                (
                    "query_url",
                    models.TextField(help_text="Full APIC query URL that was executed"),
                ),
                (
                    "query_params",
                    models.JSONField(
                        blank=True,
                        help_text="Query parameters (filters, options, etc.)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Query result data", null=True
                    ),
                ),
                (
                    "result_count",
                    models.IntegerField(
                        blank=True, help_text="Number of items in result", null=True
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        help_text="Error type (timeout, 403, 404, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Detailed error message", null=True
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "response_size_bytes",
                    models.IntegerField(
                        blank=True, help_text="Size of response in bytes", null=True
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Parent chain execution job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iterations",
                        to="queries.chainexecutionjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chain Iteration Result",
                "verbose_name_plural": "Chain Iteration Results",
                "ordering": ["job", "iteration_index"],
                "indexes": [
                    models.Index(
                        fields=["job", "iteration_index"],
                        name="queries_cha_job_id_73e13a_idx",
                    ),
                    models.Index(
                        fields=["job", "status"], name="queries_cha_job_id_1d7363_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="queries_cha_status_d7422d_idx",
                    ),
                ],
                "unique_together": {("job", "iteration_index")},
            },
        ),
        migrations.AddIndex(
            model_name="savedquery",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="queries_sav_created_72adc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedquery",
            index=models.Index(
                fields=["category", "-created_at"],
                name="queries_sav_categor_2f2e7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedquery",
            index=models.Index(
                fields=["is_validation_query", "-created_at"],
                name="queries_sav_is_vali_47cf44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="queryexecutionlog",
            index=models.Index(
                fields=["query", "-executed_at"], name="queries_que_query_i_ae2e8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryexecutionlog",
            index=models.Index(
                fields=["executed_by", "-executed_at"],
                name="queries_que_execute_e2911f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chainexecutionjob",
            index=models.Index(
                fields=["user", "-created_at"], name="queries_cha_user_id_7f93cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chainexecutionjob",
            index=models.Index(
                fields=["status", "-created_at"], name="queries_cha_status_934a31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chainexecutionjob",
            index=models.Index(
                fields=["query", "-created_at"], name="queries_cha_query_i_a7741f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="queries_sch_created_45826f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["status", "next_run_at"], name="queries_sch_status_b28945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["saved_query", "-created_at"],
                name="queries_sch_saved_q_2e88f6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtaskexecution",
            index=models.Index(
                fields=["scheduled_task", "-created_at"],
                name="queries_sch_schedul_7db8c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtaskexecution",
            index=models.Index(
                fields=["status", "-created_at"], name="queries_sch_status_cab294_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtaskexecution",
            index=models.Index(
                fields=["apic_connection_id", "-created_at"],
                name="queries_sch_apic_co_fdfd5a_idx",
            ),
        ),
    ]
