# Generated by Django 6.0.4 on 2026-05-01 13:16

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DevNetVersion",
            fields=[
                (
                    "version_key",
                    models.CharField(
                        help_text='Compact internal key, e.g. "611" for 6.1.X.',
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Human label, e.g. "6.1.X".', max_length=32
                    ),
                ),
                (
                    "url_template",
                    models.CharField(
                        help_text="URL template containing {pkg} and {class} placeholders.",
                        max_length=512,
                    ),
                ),
                (
                    "fallback_chain",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=8),
                        default=list,
                        help_text="Ordered list of version_keys to try when a class 404s.",
                    ),
                ),
                ("is_supported", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "class_count_seed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of classes in the bundled seed list for this version.",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "DevNet Version",
                "verbose_name_plural": "DevNet Versions",
                "ordering": ["-display_order", "version_key"],
            },
        ),
        migrations.CreateModel(
            name="MIMRegistryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "devnet_concurrency",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Default parallel HTTP requests for DevNet scraping (1-10). Per-run override allowed.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "devnet_request_delay_ms",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Per-request fixed delay in ms (politeness floor). Cisco DevNet is CDN-served (CloudFront/S3) and tolerates aggressive pulls; 100ms × 10 parallel ≈ 1000 req/s which has tested fine.",
                    ),
                ),
                (
                    "devnet_max_retries",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Retry attempts on 5xx / network failure before falling back to next version.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MIM Registry Config",
                "verbose_name_plural": "MIM Registry Config",
            },
        ),
        migrations.CreateModel(
            name="MIMImportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_key", models.CharField(db_index=True, max_length=8)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("init", "Initializing"),
                            ("downloading", "Downloading classes"),
                            ("importing", "Importing into Neo4j"),
                            ("finalizing", "Finalizing"),
                            ("done", "Done"),
                        ],
                        default="init",
                        max_length=24,
                    ),
                ),
                ("total_classes", models.IntegerField(default=0)),
                ("completed_count", models.IntegerField(default=0)),
                ("fallback_count", models.IntegerField(default=0)),
                ("not_found_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                (
                    "concurrency",
                    models.SmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_summary", models.TextField(blank=True, default="")),
                ("cancel_requested", models.BooleanField(default=False)),
                (
                    "core_ready_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When hot list completed and the UI became usable.",
                        null=True,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mim_import_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MIM Import Run",
                "verbose_name_plural": "MIM Import Runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MIMVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apic_version", models.CharField(max_length=32, unique=True)),
                ("class_count", models.IntegerField(default=0)),
                ("property_count", models.IntegerField(default=0)),
                ("rel_count", models.IntegerField(default=0)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mim_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MIM Version",
                "verbose_name_plural": "MIM Versions",
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="MIMImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_pkg", models.CharField(db_index=True, max_length=64)),
                (
                    "class_name",
                    models.CharField(
                        help_text='Normalized name (e.g. "fvTenant").', max_length=128
                    ),
                ),
                (
                    "qualified_name",
                    models.CharField(
                        help_text='Original colon form (e.g. "fv:Tenant").',
                        max_length=160,
                    ),
                ),
                (
                    "is_hot",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True for classes in the curated core list (hot list phase).",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("not_found", "Not found"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "source_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which devnet version actually served this class (after fallback).",
                        max_length=8,
                    ),
                ),
                (
                    "attempted_versions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=8),
                        blank=True,
                        default=list,
                    ),
                ),
                ("http_etag", models.CharField(blank=True, default="", max_length=64)),
                ("http_status_last", models.SmallIntegerField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("retry_count", models.SmallIntegerField(default=0)),
                (
                    "tmp_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Filesystem path of the cached pubhub payload; cleared after import.",
                        max_length=512,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="mim_registry.mimimportrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "MIM Import Job",
                "verbose_name_plural": "MIM Import Jobs",
                "indexes": [
                    models.Index(
                        fields=["run", "state"], name="mim_registr_run_id_cf1602_idx"
                    ),
                    models.Index(
                        fields=["run", "is_hot", "state"],
                        name="mim_registr_run_id_171a49_idx",
                    ),
                ],
                "unique_together": {("run", "class_pkg", "class_name")},
            },
        ),
    ]
