"""
Django settings for fabrik project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import logging
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: SECRET_KEY must be set via environment variable in production.
# In development, a fallback is provided. Production deployments will raise
# ValueError if this variable is missing.
_secret_key = os.getenv('DJANGO_SECRET_KEY', '')
if not _secret_key:
    import sys
    if 'test' in sys.argv or os.getenv('CI'):
        _secret_key = 'django-insecure-test-only-key-do-not-use-in-production'
    elif os.getenv('DJANGO_DEVELOPMENT', 'false').lower() == 'true':
        _secret_key = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        raise ValueError(
            "DJANGO_SECRET_KEY environment variable is not set. "
            "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
        )
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'false').lower() == 'true'

_allowed_hosts = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()] if _allowed_hosts else ['localhost', '127.0.0.1']
# In DEBUG mode, allow all hosts for development convenience
if DEBUG:
    ALLOWED_HOSTS = ['*']

# Deployment mode: 'PROD' (default) or 'DEMO'.
# Code branches off settings.FABRIK_MODE to toggle demo-only restrictions
# (read-only views, seeded data, etc.) without forking the codebase.
FABRIK_MODE = os.getenv('FABRIK_MODE', 'PROD').upper()
if FABRIK_MODE not in ('PROD', 'DEMO'):
    raise ImproperlyConfigured(
        f"FABRIK_MODE must be 'PROD' or 'DEMO', got '{FABRIK_MODE}'"
    )

# Public registration: when False (default), the /api/users/register/ endpoint
# returns 403 to anonymous callers. Admins create accounts via the user
# management UI. Set true only for lab/demo deployments where self-signup
# is intentional.
FABRIK_ALLOW_PUBLIC_REGISTRATION = os.getenv(
    'FABRIK_ALLOW_PUBLIC_REGISTRATION', 'false'
).lower() == 'true'

# Neo4j Configuration
NEO4J_URI = os.getenv('NEO4J_URI', 'bolt://neo4j:7687')
NEO4J_USER = os.getenv('NEO4J_USER', 'neo4j')
NEO4J_PASSWORD = os.getenv('NEO4J_PASSWORD', '')

# Encryption Key for APIC Passwords
# SECURITY: In production, this MUST be set via environment variable.
# Rotating this key requires re-encrypting all stored credentials.
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
_encryption_key = os.getenv('ENCRYPTION_KEY', '')
if not _encryption_key:
    import sys
    if 'test' in sys.argv or os.getenv('CI') or os.getenv('DJANGO_DEVELOPMENT', 'false').lower() == 'true':
        _encryption_key = 'rlC_Q73m6yg5bBFVz4GIfXjC61JmQ2QZT0okAzOdpJE='
    else:
        raise ValueError(
            "ENCRYPTION_KEY environment variable is not set. "
            "Generate one with: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
        )
ENCRYPTION_KEY = _encryption_key
FERNET_KEY = ENCRYPTION_KEY.encode() if isinstance(ENCRYPTION_KEY, str) else ENCRYPTION_KEY

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # Third-party apps
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'channels',

    # FABRIK apps
    'mim',
    'mim_registry',
    'queries',
    'time_machine',
    'users',
    'apic_connections',
    'audit',
    'awx',
    'notifications',
    'dashboard',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'fabrik.security_middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'audit.middleware.AuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS — env'den okunur; DEBUG modda tüm origin'lere izin verilir
_cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
if _cors_origins_env:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_env.split(',') if o.strip()]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    # Env ayarlanmamışsa: DEBUG'da wildcard, production'da güvenli varsayılan
    CORS_ALLOW_ALL_ORIGINS = DEBUG
    if not DEBUG:
        CORS_ALLOWED_ORIGINS = ['http://localhost:5173', 'http://127.0.0.1:5173']
CORS_ALLOW_CREDENTIALS = True

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '300/minute',
        # Per-endpoint rates are configured via RATE_LIMITS below and applied
        # through custom throttle classes in users.throttles. The scopes here
        # are fallback defaults used by DRF's built-in ScopedRateThrottle.
        'login': '10/minute',
        'mfa': '10/minute',
        'registration': '5/hour',
        'password_reset': '5/hour',
        'token_refresh': '30/minute',
        'email_verify': '10/hour',
        'email_send': '5/hour',
        'webhook': '120/minute',
        'sensitive_action': '10/hour',
    },
}

# Rate limits for security-sensitive endpoints. Override via environment:
#   RATE_LIMIT_LOGIN=20/minute  (parsed below)
# Each key maps to a throttle scope in users.throttles.
_rate_limit_defaults = {
    'login': '10/minute',
    'mfa': '10/minute',
    'registration': '5/hour',
    'password_reset': '5/hour',
    'token_refresh': '30/minute',
    'email_verify': '10/hour',
    'email_send': '5/hour',
    'webhook': '120/minute',
    'sensitive_action': '10/hour',
}

RATE_LIMITS = {}
for _scope, _default in _rate_limit_defaults.items():
    RATE_LIMITS[_scope] = os.getenv(f'RATE_LIMIT_{_scope.upper()}', _default)

# OpenAPI / Swagger (drf-spectacular)
SPECTACULAR_SETTINGS = {
    'TITLE': 'FABRIK API',
    'VERSION': '1.0.1',
    'DESCRIPTION': 'Visualise, Query, and Automate Your Cisco ACI Fabric — Without Writing API Calls.',
    'SCHEMA_PATH_PREFIX': '/api/',
    'SERVE_INCLUDE_SCHEMA': False,
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


ROOT_URLCONF = 'fabrik.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fabrik.wsgi.application'
ASGI_APPLICATION = 'fabrik.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'fabrik'),
        'USER': os.getenv('POSTGRES_USER', 'fabrik'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', 'postgres'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (exports, uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redis Configuration (for Celery broker and cache)
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379')

# Notification retention (days). Read notifications are cleaned up sooner because
# the user has already seen them; unread ones stick around longer as a safety net.
NOTIFICATION_RETENTION_READ_DAYS = int(os.getenv('NOTIFICATION_RETENTION_READ_DAYS', '90'))
NOTIFICATION_RETENTION_UNREAD_DAYS = int(os.getenv('NOTIFICATION_RETENTION_UNREAD_DAYS', '180'))

# Email delivery — defaults to console backend for dev, configure SMTP for production.
# EMAIL_ENABLED is auto-detected from EMAIL_HOST presence, or can be set explicitly.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@fabrikops.com')
NOTIFICATION_EMAIL_ENABLED = os.getenv('NOTIFICATION_EMAIL_ENABLED', 'false').lower() == 'true'

# Auto-detect: if no EMAIL_HOST configured and backend is SMTP, email is disabled.
# Console/locmem backends count as "enabled" for dev purposes.
_email_enabled_env = os.getenv('EMAIL_ENABLED', '').lower()
if _email_enabled_env:
    EMAIL_ENABLED = _email_enabled_env == 'true'
else:
    EMAIL_ENABLED = bool(EMAIL_HOST) or 'console' in EMAIL_BACKEND or 'locmem' in EMAIL_BACKEND

# Celery Configuration
CELERY_BROKER_URL = f'{REDIS_URL}/0'
CELERY_RESULT_BACKEND = f'{REDIS_URL}/1'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Cache Configuration (Django cache framework with Redis)
# IGNORE_EXCEPTIONS: if Redis is temporarily unreachable, cache operations
# return None instead of raising ConnectionError. Without this, any Redis
# hiccup breaks throttled endpoints (MFA verify, password reset, etc.) with
# a 500 response — user never gets backup codes, password reset emails, etc.
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'{REDIS_URL}/2',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'fabrik',
        'TIMEOUT': 300,  # 5 minutes default
    }
}
DJANGO_REDIS_IGNORE_EXCEPTIONS = True
DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True

# Site URL (for email links and password reset URLs)
SITE_URL = os.getenv('SITE_URL', 'http://localhost:3000')

# Default quotas — fallback when user has no group quota assigned
DEFAULT_QUOTAS = {
    'max_saved_queries': 0,        # 0 = unlimited
    'max_scheduled_tasks': 0,
    'max_apic_connections': 0,
    'max_awx_requests_daily': 0,
    'max_awx_concurrent': 5,
    'max_query_results': 0,
    'max_export_rows': 50000,
    'query_execution_daily': 0,
    'can_create_queries': True,
    'can_execute_queries': True,
    'can_create_scheduled': True,
    'can_use_awx': True,
    'can_use_time_machine': True,
    'can_export_data': True,
    'can_share_resources': True,
    'can_use_ai_builder': True,
    'ai_analysis_daily': 0,            # 0 = unlimited
}

# Django Channels Configuration (WebSocket support)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.getenv('REDIS_HOST', 'redis'), int(os.getenv('REDIS_PORT', 6379)))],
        },
    },
}

# =============================================================================
# LDAP Configuration (Enterprise Authentication)
# =============================================================================

# Enable/disable LDAP authentication via environment variable
LDAP_ENABLED = os.getenv('LDAP_ENABLED', 'false').lower() == 'true'

if LDAP_ENABLED:
    # Import LDAP modules (only if enabled)
    try:
        import ldap
        from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

        # LDAP Server Configuration
        AUTH_LDAP_SERVER_URI = os.getenv('LDAP_SERVER_URI', 'ldap://ldap.company.com')
        AUTH_LDAP_BIND_DN = os.getenv('LDAP_BIND_DN', 'cn=admin,dc=company,dc=com')
        AUTH_LDAP_BIND_PASSWORD = os.getenv('LDAP_BIND_PASSWORD', '')

        # Connection timeout — prevents Daphne from hanging when LDAP server is unreachable
        AUTH_LDAP_CONNECTION_OPTIONS = {
            ldap.OPT_NETWORK_TIMEOUT: 3,
            ldap.OPT_TIMEOUT: 3,
            ldap.OPT_REFERRALS: 0,
        }

        # User Search Configuration
        AUTH_LDAP_USER_SEARCH = LDAPSearch(
            os.getenv('LDAP_USER_DN', 'ou=users,dc=company,dc=com'),
            ldap.SCOPE_SUBTREE,
            "(uid=%(user)s)"
        )

        # User Attribute Mapping
        AUTH_LDAP_USER_ATTR_MAP = {
            'first_name': 'givenName',
            'last_name': 'sn',
            'email': 'mail',
            # LDAP custom attributes (will be added to User model via getattr)
            'department': 'department',
            'employee_id': 'employeeNumber',
            'job_title': 'title',
            'phone_number': 'telephoneNumber',
            'manager': 'manager',
            'office_location': 'physicalDeliveryOfficeName',
        }

        # Group Search Configuration
        AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
            os.getenv('LDAP_GROUP_DN', 'ou=groups,dc=company,dc=com'),
            ldap.SCOPE_SUBTREE,
            "(objectClass=groupOfNames)"
        )
        AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()

        # Mirror LDAP groups to Django groups
        AUTH_LDAP_MIRROR_GROUPS = True

        # Always update user profile from LDAP on login
        AUTH_LDAP_ALWAYS_UPDATE_USER = True

        # Populate user profile on first login
        AUTH_LDAP_USER_FLAGS_BY_GROUP = {
            "is_active": os.getenv('LDAP_ACTIVE_GROUP', 'cn=active,ou=groups,dc=company,dc=com'),
            "is_staff": os.getenv('LDAP_STAFF_GROUP', 'cn=staff,ou=groups,dc=company,dc=com'),
            "is_superuser": os.getenv('LDAP_ADMIN_GROUP', 'cn=admins,ou=groups,dc=company,dc=com'),
        }

        # Local auth only in AUTHENTICATION_BACKENDS — LDAP login has its own
        # dedicated endpoint (/api/auth/ldap-login/) so an unreachable LDAP
        # server can never block normal login.
        AUTHENTICATION_BACKENDS = [
            'django.contrib.auth.backends.ModelBackend',
        ]

        logging.getLogger('django').info("LDAP authentication ENABLED")

    except ImportError:
        logging.getLogger('django').warning("LDAP enabled but django-auth-ldap not installed. Install with: pip install django-auth-ldap python-ldap")
        logging.getLogger('django').warning("Falling back to standard Django authentication")
        AUTHENTICATION_BACKENDS = [
            'django.contrib.auth.backends.ModelBackend',
        ]
else:
    # Standard Django authentication only
    AUTHENTICATION_BACKENDS = [
        'django.contrib.auth.backends.ModelBackend',
    ]
    logging.getLogger('django').info("LDAP authentication DISABLED (using local Django auth)")

# =============================================================================
# Fabrik Platform Configuration
# =============================================================================

# Platform metadata (used in audit trails and extra_vars)
FABRIK_VERSION = os.getenv('FABRIK_VERSION', '1.0.1')
FABRIK_BASE_URL = os.getenv('FABRIK_BASE_URL', 'http://localhost:3000')

# Feature Flags
FABRIK_FEATURES = {
    'LDAP_ENABLED': LDAP_ENABLED,
    'AWX_USER_MAPPING': os.getenv('AWX_USER_MAPPING', 'false').lower() == 'true',
    'SYSLOG_AUDIT': os.getenv('SYSLOG_AUDIT', 'false').lower() == 'true',
}

# AWX Execution Settings
AWX_DEFAULT_EXECUTION_MODE = os.getenv('AWX_DEFAULT_EXECUTION_MODE', 'bulk')
AWX_MAX_CONCURRENT_PER_USER = int(os.getenv('AWX_MAX_CONCURRENT_PER_USER', '5'))
AWX_MAX_CONCURRENT_GLOBAL = int(os.getenv('AWX_MAX_CONCURRENT_GLOBAL', '20'))

# Job Monitoring
AWX_JOB_SYNC_INTERVAL = int(os.getenv('AWX_JOB_SYNC_INTERVAL', '10'))  # seconds

# Validation Polling (Admin configurable)
AWX_VALIDATION_POLLING_INTERVAL = int(os.getenv('AWX_VALIDATION_POLLING_INTERVAL', '2'))  # seconds

# Logging Configuration (optional: detailed LDAP logs)
if LDAP_ENABLED and os.getenv('LDAP_DEBUG', 'false').lower() == 'true':
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django_auth_ldap': {
                'handlers': ['console'],
                'level': 'DEBUG',
            },
        },
    }
