# Generated by Django 6.0.4 on 2026-05-01 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("queries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeMachineSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "retention_policy",
                    models.CharField(
                        choices=[
                            ("unlimited", "Unlimited"),
                            ("days", "By Days"),
                            ("count", "By Count"),
                        ],
                        default="days",
                        max_length=20,
                    ),
                ),
                ("retention_days", models.IntegerField(default=30)),
                ("retention_count", models.IntegerField(default=100)),
                ("max_snapshot_size_mb", models.FloatField(default=10.0)),
                ("warn_large_snapshots", models.BooleanField(default=True)),
                ("auto_cleanup_enabled", models.BooleanField(default=True)),
                ("store_duplicates", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_machine_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Machine Settings",
                "verbose_name_plural": "Time Machine Settings",
                "db_table": "time_machine_settings",
            },
        ),
        migrations.CreateModel(
            name="QueryExecutionSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_name", models.CharField(db_index=True, max_length=255)),
                ("class_name", models.CharField(db_index=True, max_length=100)),
                (
                    "query_version_hash",
                    models.CharField(db_index=True, default="", max_length=8),
                ),
                ("major_version", models.IntegerField(default=1)),
                ("minor_version", models.IntegerField(default=0)),
                (
                    "execution_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Execution"),
                            ("scheduled", "Scheduled Execution"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("query_structure", models.JSONField(blank=True, null=True)),
                ("result_data", models.JSONField()),
                ("result_count", models.IntegerField(default=0)),
                ("result_size_bytes", models.BigIntegerField(default=0)),
                ("executed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("apic_connection_id", models.IntegerField(db_index=True)),
                ("apic_connection_name", models.CharField(max_length=200)),
                (
                    "scheduled_task_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "scheduled_task_execution_id",
                    models.UUIDField(blank=True, null=True),
                ),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("result_hash", models.CharField(db_index=True, max_length=64)),
                ("has_changes", models.BooleanField(db_index=True, default=False)),
                ("annotation", models.TextField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_machine_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saved_query",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_machine_snapshots",
                        to="queries.savedquery",
                    ),
                ),
            ],
            options={
                "db_table": "time_machine_snapshots",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["saved_query", "-executed_at"],
                        name="queries_que_saved_q_execut_idx",
                    ),
                    models.Index(
                        fields=["saved_query", "query_version_hash", "-executed_at"],
                        name="queries_que_saved_q_query__idx",
                    ),
                    models.Index(
                        fields=["class_name", "-executed_at"],
                        name="queries_que_class_n_execut_idx",
                    ),
                    models.Index(
                        fields=["executed_by", "-executed_at"],
                        name="queries_que_execute_execut_idx",
                    ),
                    models.Index(
                        fields=["apic_connection_id", "-executed_at"],
                        name="queries_que_apic_co_execut_idx",
                    ),
                    models.Index(
                        fields=["execution_type", "-executed_at"],
                        name="queries_que_executi_execut_idx",
                    ),
                    models.Index(
                        fields=["result_hash"], name="queries_que_result__idx"
                    ),
                    models.Index(
                        fields=["saved_query", "has_changes", "-executed_at"],
                        name="tm_sq_haschanges_idx",
                    ),
                ],
            },
        ),
    ]
