# Generated by Django 6.0.4 on 2026-05-01 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupQuota",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="quota",
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                (
                    "max_saved_queries",
                    models.PositiveIntegerField(
                        default=0, help_text="Max saved queries (0=unlimited)"
                    ),
                ),
                (
                    "max_scheduled_tasks",
                    models.PositiveIntegerField(
                        default=0, help_text="Max scheduled tasks (0=unlimited)"
                    ),
                ),
                (
                    "max_apic_connections",
                    models.PositiveIntegerField(
                        default=0, help_text="Max APIC connections (0=unlimited)"
                    ),
                ),
                (
                    "max_awx_requests_daily",
                    models.PositiveIntegerField(
                        default=0, help_text="Max AWX requests per day (0=unlimited)"
                    ),
                ),
                (
                    "max_awx_concurrent",
                    models.PositiveIntegerField(
                        default=5, help_text="Max concurrent AWX jobs"
                    ),
                ),
                (
                    "max_query_results",
                    models.PositiveIntegerField(
                        default=0, help_text="Max result rows returned (0=unlimited)"
                    ),
                ),
                (
                    "max_export_rows",
                    models.PositiveIntegerField(
                        default=50000, help_text="Max CSV/JSON export rows"
                    ),
                ),
                (
                    "query_execution_daily",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Max background query executions per day (0=unlimited)",
                    ),
                ),
                ("can_create_queries", models.BooleanField(default=True)),
                ("can_execute_queries", models.BooleanField(default=True)),
                ("can_create_scheduled", models.BooleanField(default=True)),
                ("can_use_awx", models.BooleanField(default=True)),
                ("can_use_time_machine", models.BooleanField(default=True)),
                ("can_export_data", models.BooleanField(default=True)),
                ("can_share_resources", models.BooleanField(default=True)),
                ("can_use_ai_builder", models.BooleanField(default=True)),
                (
                    "ai_analysis_daily",
                    models.PositiveIntegerField(
                        default=0, help_text="Max AI analyses per day (0=unlimited)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Quota",
                "verbose_name_plural": "Group Quotas",
                "db_table": "users_group_quota",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "display_timezone",
                    models.CharField(
                        choices=[
                            ("UTC", "UTC (Coordinated Universal Time)"),
                            ("Europe/Istanbul", "Europe/Istanbul (UTC+3)"),
                            ("Europe/London", "Europe/London (UTC+0/+1)"),
                            ("Europe/Paris", "Europe/Paris (UTC+1/+2)"),
                            ("Europe/Berlin", "Europe/Berlin (UTC+1/+2)"),
                            ("America/New_York", "America/New York (UTC-5/-4)"),
                            ("America/Chicago", "America/Chicago (UTC-6/-5)"),
                            ("America/Los_Angeles", "America/Los Angeles (UTC-8/-7)"),
                            ("Asia/Tokyo", "Asia/Tokyo (UTC+9)"),
                            ("Asia/Dubai", "Asia/Dubai (UTC+4)"),
                            ("Asia/Singapore", "Asia/Singapore (UTC+8)"),
                            ("Australia/Sydney", "Australia/Sydney (UTC+10/+11)"),
                        ],
                        default="Europe/Istanbul",
                        help_text="Timezone for displaying dates and times in the UI",
                        max_length=50,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("DD/MM/YYYY", "DD/MM/YYYY (European)"),
                            ("MM/DD/YYYY", "MM/DD/YYYY (US)"),
                            ("YYYY-MM-DD", "YYYY-MM-DD (ISO)"),
                        ],
                        default="DD/MM/YYYY",
                        help_text="Preferred date format",
                        max_length=20,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[
                            ("24h", "24-hour (14:30)"),
                            ("12h", "12-hour (2:30 PM)"),
                        ],
                        default="24h",
                        help_text="Preferred time format (12-hour or 24-hour)",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this profile was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this profile was last updated"
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Consecutive failed login attempts"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Account locked until this datetime (None = not locked)",
                        null=True,
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.PositiveIntegerField(
                        default=480,
                        help_text="Auto-logout after this many minutes of inactivity (0 = never)",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has verified their email address",
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When the email was verified", null=True
                    ),
                ),
                (
                    "totp_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Base32-encoded TOTP secret (empty = MFA not set up)",
                        max_length=64,
                    ),
                ),
                (
                    "totp_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether TOTP MFA is active for this user",
                    ),
                ),
                (
                    "backup_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Hashed backup codes for MFA recovery",
                    ),
                ),
                (
                    "auth_source",
                    models.CharField(
                        choices=[("local", "Local"), ("ldap", "LDAP")],
                        default="local",
                        help_text="Where this user authenticates — local Django DB or LDAP",
                        max_length=10,
                    ),
                ),
                (
                    "share_class_telemetry",
                    models.BooleanField(
                        default=True,
                        help_text="Include this user's class usage in org-wide trending aggregates",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "users_userprofile",
                "ordering": ["user__username"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="Hashed reset code (never store plain text)",
                        max_length=128,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Code expires after this datetime"),
                ),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin who generated this code",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reset_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_password_reset_code",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="usr_prc_user_created_idx"
                    )
                ],
            },
        ),
    ]
