# Generated by Django 6.0.4 on 2026-05-01 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogSettings",
            fields=[
                (
                    "id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                (
                    "user_management_enabled",
                    models.BooleanField(
                        default=True, help_text="Log user create/edit/delete"
                    ),
                ),
                (
                    "group_permission_enabled",
                    models.BooleanField(
                        default=True, help_text="Log group and permission changes"
                    ),
                ),
                (
                    "login_logout_enabled",
                    models.BooleanField(
                        default=True, help_text="Log authentication events"
                    ),
                ),
                (
                    "apic_management_enabled",
                    models.BooleanField(
                        default=True, help_text="Log APIC connection CRUD and queries"
                    ),
                ),
                (
                    "query_content_enabled",
                    models.BooleanField(
                        default=True, help_text="Log query text and responses"
                    ),
                ),
                (
                    "task_management_enabled",
                    models.BooleanField(
                        default=True, help_text="Log scheduled task operations"
                    ),
                ),
                (
                    "time_machine_enabled",
                    models.BooleanField(
                        default=True, help_text="Log time machine operations"
                    ),
                ),
                (
                    "awx_management_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Log AWX connection and template changes",
                    ),
                ),
                (
                    "awx_automation_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Log automation request and execution events",
                    ),
                ),
                (
                    "settings_changes_enabled",
                    models.BooleanField(default=True, help_text="Log settings updates"),
                ),
                (
                    "mim_explorer_enabled",
                    models.BooleanField(
                        default=True, help_text="Log MIM sync operations"
                    ),
                ),
                (
                    "api_access_enabled",
                    models.BooleanField(
                        default=False, help_text="Log all API endpoint access"
                    ),
                ),
                ("user_management_retention_days", models.IntegerField(default=365)),
                ("group_permission_retention_days", models.IntegerField(default=365)),
                ("login_logout_retention_days", models.IntegerField(default=90)),
                ("apic_management_retention_days", models.IntegerField(default=180)),
                ("query_content_retention_days", models.IntegerField(default=90)),
                ("task_management_retention_days", models.IntegerField(default=180)),
                ("time_machine_retention_days", models.IntegerField(default=90)),
                ("awx_management_retention_days", models.IntegerField(default=365)),
                ("awx_automation_retention_days", models.IntegerField(default=365)),
                ("settings_changes_retention_days", models.IntegerField(default=365)),
                ("mim_explorer_retention_days", models.IntegerField(default=90)),
                ("api_access_retention_days", models.IntegerField(default=30)),
                (
                    "max_content_size_mb",
                    models.IntegerField(
                        default=10, help_text="Max size for query content in MB"
                    ),
                ),
                (
                    "compress_large_content",
                    models.BooleanField(
                        default=True, help_text="Compress content > 1MB"
                    ),
                ),
                ("auto_cleanup_enabled", models.BooleanField(default=True)),
                (
                    "cleanup_time_hour",
                    models.IntegerField(
                        default=3, help_text="Hour of day (0-23) to run cleanup"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Settings",
                "verbose_name_plural": "Audit Log Settings",
                "db_table": "audit_log_settings",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("user_management", "User Management"),
                            ("group_permission", "Group & Permission"),
                            ("login_logout", "Login/Logout"),
                            ("apic_management", "APIC Connection Management"),
                            ("query_management", "Query Management"),
                            ("query_execution", "Query Execution"),
                            ("category_management", "Query Category Management"),
                            ("task_management", "Scheduled Task Management"),
                            ("time_machine", "Time Machine"),
                            ("awx_management", "AWX Connection & Template Management"),
                            ("awx_automation", "AWX Automation Execution"),
                            ("awx_webhook", "AWX Webhook Events"),
                            ("validation", "Data Validation"),
                            ("validation_management", "Validation List Management"),
                            ("notification_management", "Notification Management"),
                            ("settings_change", "Settings Change"),
                            ("system_settings", "System Settings"),
                            ("api_access", "API Access"),
                            ("mim_explorer", "MIM Explorer"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("user_activated", "User Activated"),
                            ("user_deactivated", "User Deactivated"),
                            ("password_reset", "Password Reset"),
                            ("group_created", "Group Created"),
                            ("group_updated", "Group Updated"),
                            ("group_deleted", "Group Deleted"),
                            ("group_cloned", "Group Cloned"),
                            ("permissions_added", "Permissions Added"),
                            ("permissions_removed", "Permissions Removed"),
                            ("login_success", "Login Success"),
                            ("login_failed", "Login Failed"),
                            ("logout", "Logout"),
                            ("apic_connection_created", "APIC Connection Created"),
                            ("apic_connection_updated", "APIC Connection Updated"),
                            ("apic_connection_deleted", "APIC Connection Deleted"),
                            ("apic_connection_tested", "APIC Connection Tested"),
                            (
                                "apic_connection_test_permission_denied",
                                "APIC Connection Test Permission Denied",
                            ),
                            (
                                "apic_connection_test_password_error",
                                "APIC Connection Test Password Error",
                            ),
                            ("apic_query_executed", "APIC Query Executed"),
                            (
                                "apic_query_validation_failed",
                                "APIC Query Validation Failed",
                            ),
                            (
                                "apic_query_connection_not_found",
                                "APIC Query Connection Not Found",
                            ),
                            (
                                "apic_query_permission_denied",
                                "APIC Query Permission Denied",
                            ),
                            (
                                "apic_query_inactive_connection",
                                "APIC Query Inactive Connection",
                            ),
                            ("apic_query_password_error", "APIC Query Password Error"),
                            ("query_created", "Query Created"),
                            ("query_updated", "Query Updated"),
                            ("query_deleted", "Query Deleted"),
                            ("query_duplicated", "Query Duplicated"),
                            ("query_executed", "Query Executed"),
                            ("background_query_started", "Background Query Started"),
                            (
                                "background_query_cancelled",
                                "Background Query Cancelled",
                            ),
                            ("category_created", "Query Category Created"),
                            ("category_updated", "Query Category Updated"),
                            ("category_deleted", "Query Category Deleted"),
                            ("scheduled_task_created", "Scheduled Task Created"),
                            ("scheduled_task_updated", "Scheduled Task Updated"),
                            ("scheduled_task_deleted", "Scheduled Task Deleted"),
                            ("scheduled_task_paused", "Scheduled Task Paused"),
                            ("scheduled_task_resumed", "Scheduled Task Resumed"),
                            (
                                "scheduled_task_executed_manually",
                                "Scheduled Task Executed Manually",
                            ),
                            ("scheduled_task_cloned", "Scheduled Task Cloned"),
                            (
                                "time_machine_snapshot_captured",
                                "Time Machine Snapshot Captured",
                            ),
                            (
                                "time_machine_snapshot_failed",
                                "Time Machine Snapshot Failed",
                            ),
                            (
                                "time_machine_snapshots_compared",
                                "Time Machine Snapshots Compared",
                            ),
                            (
                                "time_machine_settings_updated",
                                "Time Machine Settings Updated",
                            ),
                            (
                                "time_machine_cleanup_executed",
                                "Time Machine Cleanup Executed",
                            ),
                            ("awx_connection_created", "AWX Connection Created"),
                            ("awx_connection_updated", "AWX Connection Updated"),
                            ("awx_connection_deleted", "AWX Connection Deleted"),
                            ("awx_connection_tested", "AWX Connection Tested"),
                            ("ansible_template_created", "Automation Template Created"),
                            ("ansible_template_updated", "Automation Template Updated"),
                            ("ansible_template_deleted", "Automation Template Deleted"),
                            ("template_category_updated", "Template Category Updated"),
                            ("template_category_deleted", "Template Category Deleted"),
                            (
                                "template_validation_started",
                                "Template Validation Started",
                            ),
                            ("template_sheets_validated", "Template Sheets Validated"),
                            (
                                "automation_request_created",
                                "Automation Request Created",
                            ),
                            (
                                "automation_request_updated",
                                "Automation Request Updated",
                            ),
                            (
                                "automation_request_deleted",
                                "Automation Request Deleted",
                            ),
                            (
                                "automation_request_execution_triggered",
                                "Automation Request Execution Triggered",
                            ),
                            (
                                "automation_execution_retry_triggered",
                                "Automation Execution Retry Triggered",
                            ),
                            (
                                "automation_execution_cancelled",
                                "Automation Execution Cancelled",
                            ),
                            (
                                "execute_automation_request",
                                "Automation Request Executed",
                            ),
                            (
                                "execute_automation_request_failed",
                                "Automation Request Execution Failed",
                            ),
                            ("awx_webhook_received", "AWX Webhook Received"),
                            ("validation_list_created", "Validation List Created"),
                            ("validation_list_updated", "Validation List Updated"),
                            ("validation_list_deleted", "Validation List Deleted"),
                            ("notification_deleted", "Notification Deleted"),
                            ("settings_updated", "Settings Updated"),
                            ("audit_settings_updated", "Audit Settings Updated"),
                            (
                                "task_management_settings_updated",
                                "Task Management Settings Updated",
                            ),
                            ("ai_settings_updated", "AI Settings Updated"),
                            ("mim_sync_started", "MIM Sync Started"),
                            ("mim_sync_completed", "MIM Sync Completed"),
                            ("mim_sync_failed", "MIM Sync Failed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("resource_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("content", models.TextField(blank=True)),
                ("content_size", models.IntegerField(default=0)),
                ("content_truncated", models.BooleanField(default=False)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_log_timesta_8b04a8_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_log_user_id_79f582_idx",
                    ),
                    models.Index(
                        fields=["category", "-timestamp"],
                        name="audit_log_categor_e8011f_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_log_action_cf8063_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_log_resourc_2570dd_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("success", models.BooleanField(db_index=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_login_attempt",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_login_timesta_078f95_idx"
                    ),
                    models.Index(
                        fields=["username", "-timestamp"],
                        name="audit_login_usernam_193c85_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="audit_login_ip_addr_f70a24_idx",
                    ),
                    models.Index(
                        fields=["success", "-timestamp"],
                        name="audit_login_success_8dcf69_idx",
                    ),
                ],
            },
        ),
    ]
