# Generated by Django 6.0.4 on 2026-05-01 13:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APICConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this APIC connection",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "url",
                    models.URLField(
                        help_text="APIC URL (e.g., https://sandboxapicdc.cisco.com)",
                        max_length=255,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                (
                    "encrypted_password",
                    models.BinaryField(help_text="Encrypted password"),
                ),
                (
                    "verify_ssl",
                    models.BooleanField(
                        default=True, help_text="Verify SSL certificates"
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        default=30, help_text="Request timeout in seconds"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Allow all users to use this connection",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_status", models.BooleanField(blank=True, null=True)),
                ("last_test_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apic_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_apic_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "APIC Connection",
                "verbose_name_plural": "APIC Connections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="apic_connec_created_fa8315_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="apic_connec_is_acti_6ce932_idx",
                    ),
                ],
            },
        ),
    ]
